name: Deployment pipeline

on:
  push:
    branches:
      - 11.20
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  CI:
    timeout-minutes: 5
    runs-on: ubuntu-20.04
    concurrency: deploy-group 
    steps:
      - run: echo "CI started"
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      # - name: build error notification
      #   uses: rjstone/discord-webhook-notify@v1
      #   if: failure()
      #   with:
      #     text: Build failed
      #     severity: error
      #     description:  commit
      #     details:  https://github.com/${{github.repository}}/commit/${{github.sha}} by ${{github.triggering_actor}} broke the build :(
      #     webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      

  CD:
    if: ${{ github.event_name == 'pull_request' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
    runs-on: ubuntu-20.04
    concurrency: deploy-group 
    steps:
      - run: echo "CD started"
      - name: Trigger deployment
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
      # - name: successful deployment notification
      #   uses: rjstone/discord-webhook-notify@v1
      #   if: success()
      #   with:
      #     text: A new version of Phonebook deployed
      #     severity: info
      #     description: to https://phonebook-backend-lt41.onrender.com by ${{github.triggering_actor}}
      #     webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}


  tag_release:
    needs: [CI, CD]
    runs-on: ubuntu-20.04
    steps:
      - run: echo "tags started"
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch